'use strict';
let onlineRevision=null,onlineBusy=false,sellerSignedIn=false;



const apiURL=resource=>'/api/v1/'+resource;
function apiError(data){if(typeof data.detail==='string')return data.detail;if(Array.isArray(data.detail))return data.detail.map(d=>d.msg).join(' ');return data.error||'Request failed';}
async function sellerAPI(resource,options={}){const token=await sellerAuth.accessToken();const headers={...(options.headers||{}),...(token?{Authorization:'Bearer '+token}:{})};const request={...options,headers};const r=await fetch(apiURL(resource),{cache:'no-store',signal:AbortSignal.timeout(20000),...request});let data;try{data=await r.json();}catch{sellerEl('connectionHelp').hidden=false;throw Error('The Bindr server could not be reached.');}if(!r.ok){if(r.status===401){sellerSignedIn=false;sellerEl('sellerAuth').hidden=false;if(sellerEl('sellerEditor').open){sellerEl('reauthDialog').appendChild(sellerEl('sellerAuth'));if(!sellerEl('reauthDialog').open)sellerEl('reauthDialog').showModal();}}throw Error(apiError(data));}return data;}
function setOnlineBusy(value){onlineBusy=value;document.querySelectorAll('#sellerEditor button,#sellerEditor input,#sellerEditor select,#sellerEditor textarea,#sellerGrid button,#newListing,#reloadInventory,#logoutSeller,.marketplace-panel button,.marketplace-panel input,.marketplace-panel select').forEach(b=>b.disabled=value||b.dataset.up==='0');sellerEl('sellerDraftCount').textContent=value?'Working…':'Live binder connected';}
async function loadOnlineSeller(){const data=await sellerAPI('listings');inventory=structuredClone(data.cards);onlineRevision=data.revision;originalInventory.clear();inventory.forEach(c=>originalInventory.set(c.id,JSON.stringify(c)));sellerList();sellerEl('sellerDraftCount').textContent='Live binder connected';if(typeof renderDraftShelf==='function')await renderDraftShelf();}
async function publishCard(card){if(typeof ebayLinks==='function' && card.ebayListings===undefined){const links=ebayLinks(card);if(links.length)card={...card,ebayListings:links};}if(!sellerSignedIn)throw Error('Sign in before saving.');const data=await sellerAPI('listings/'+encodeURIComponent(card.id),{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({card})});inventory=structuredClone(data.cards);onlineRevision=data.revision;originalInventory.clear();inventory.forEach(c=>originalInventory.set(c.id,JSON.stringify(c)));sellerList();}
markSellerSold=async id=>{if(onlineBusy)return;const c=inventory.find(c=>c.id===id);if(!c)return;const previousSold=!!c.sold;sellerEl('sellerUndo').hidden=true;setOnlineBusy(true);try{await publishCard({...c,sold:!c.sold});sellerMessage(`${c.name}: marked ${!c.sold?'sold':'available'} on your live binder.`);const undo=sellerEl('sellerUndo');undo.hidden=false;undo.onclick=async()=>{if(onlineBusy)return;setOnlineBusy(true);try{const current=inventory.find(card=>card.id===id);if(!current)throw Error('This card no longer exists.');await publishCard({...current,sold:previousSold});undo.hidden=true;sellerMessage('Availability restored on the live binder.');}catch(e){sellerMessage(e.message);}finally{setOnlineBusy(false);}};}catch(e){sellerMessage(e.message+' Your screen has not been changed. Reload inventory to check.');}finally{setOnlineBusy(false);}};
sellerEl('sellerForm').onsubmit=async e=>{e.preventDefault();if(onlineBusy)return;if(typeof validateSellerDraft==='function'&&!validateSellerDraft())return;if(typeof confirmPartialUploadSave==='function'&&!confirmPartialUploadSave())return;if(!workingPhotos.length){sellerMessage('Add at least one photo.');return;}const card={...editing,name:sellerEl('sellerName').value.trim(),set:sellerEl('sellerSet').value.trim(),price:Number(sellerEl('sellerPrice').value),condition:sellerEl('sellerCondition').value,sold:sellerEl('sellerAvailability').value==='sold',description:sellerEl('sellerDescription').value.trim(),photos:[...workingPhotos],photoRoles:[...workingRoles],photoFrames:Object.fromEntries(Object.entries(workingFrames).filter(([url])=>workingPhotos.includes(url))),thumb:workingPhotos[0]===editing.photos[0]?editing.thumb:workingPhotos[0]};setOnlineBusy(true);try{await publishCard(card);editing=inventory.find(c=>c.id===card.id);dirty=false;if(typeof completeSellerDraft==='function')await completeSellerDraft();setOnlineBusy(false);await closeSellerEditor();sellerMessage('Saved to your live binder.');}catch(e){sellerMessage(e.message+' Your edits are still here.');}finally{setOnlineBusy(false);}};
async function enterSellerBinder(){sellerSignedIn=true;if(!sellerEl('sellerEditor').open)await loadOnlineSeller();sellerEl('sellerAuth').hidden=true;if(sellerEl('reauthDialog').open){sellerEl('reauthDialog').close();document.body.insertBefore(sellerEl('sellerAuth'),sellerEl('onlineSellerMain'));sellerMessage('Signed in again. Your edits are preserved; press Save to retry.');}sellerEl('onlineSellerMain').hidden=false;}
sellerEl('loginForm').onsubmit=async e=>{e.preventDefault();const b=sellerEl('sellerLogin');b.disabled=true;sellerEl('loginStatus').textContent='';try{await sellerAuth.signIn(sellerEl('sellerEmail').value.trim(),sellerEl('sellerPassword').value);sellerEl('sellerPassword').value='';try{await sellerAPI('session');}catch(e){await sellerAuth.signOut();throw e;}await enterSellerBinder();}catch(e){sellerEl('loginStatus').textContent=e.message;}finally{b.disabled=false;}};
sellerEl('reloadInventory').onclick=async()=>{if(onlineBusy)return;if(dirty&&!confirm('Discard unsaved edits and reload live inventory?'))return;try{await loadOnlineSeller();sellerEl('sellerUndo').hidden=true;sellerMessage('Latest inventory loaded.');}catch(e){sellerMessage(e.message);}};
sellerEl('logoutSeller').onclick=async()=>{if(dirty&&!confirm('Discard unsaved edits and sign out?'))return;try{await sellerAuth.signOut();dirty=false;location.reload();}catch(e){sellerMessage(e.message);}};
(async()=>{try{if(!await sellerAuth.accessToken())return;await sellerAPI('session');await enterSellerBinder();}catch(e){sellerEl('loginStatus').textContent=e.message;}})();


sellerEl('deleteSellerListing').onclick=async()=>{
 if(onlineBusy||!editing)return;
 if(!sellerSignedIn){sellerMessage('Sign in before deleting.');return;}
 const target=editing;
 if(!confirm(`Delete ${target.name||'this unsaved listing'}? It will be removed entirely, including from Sold. This cannot be undone.`))return;
 const persisted=originalInventory.has(target.id);
 setOnlineBusy(true);
 try{
  if(persisted){const data=await sellerAPI('listings/'+encodeURIComponent(target.id)+'?version='+target.version,{method:'DELETE'});inventory=structuredClone(data.cards);onlineRevision=data.revision;originalInventory.clear();inventory.forEach(c=>originalInventory.set(c.id,JSON.stringify(c)));}
  else inventory=inventory.filter(c=>c.id!==target.id);
  dirty=false;if(typeof completeSellerDraft==='function')await completeSellerDraft();editing=null;sellerEl('sellerUndo').hidden=true;setOnlineBusy(false);closeSellerEditor();sellerMessage(persisted?'Listing deleted from the live binder. It will not appear in Sold.':'Unsaved listing discarded.');
 }catch(e){sellerMessage(e.message+' Deletion was not confirmed. Reload inventory to check before trying again.');}
 finally{setOnlineBusy(false);}
};
