import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
import {cleanCard,normalizeCardMetadata,createHandler,sessionToken} from './server/core.mjs';
const cards=JSON.parse(fs.readFileSync(new URL('./inventory.json',import.meta.url))).cards.map(normalizeCardMetadata);
const ctx={URLSearchParams,structuredClone,Date};vm.createContext(ctx);
vm.runInContext(fs.readFileSync(new URL('./frontend/helpers.js',import.meta.url),'utf8')+fs.readFileSync(new URL('./frontend/marketplace.js',import.meta.url),'utf8'),ctx);
ctx.cards=cards;
assert.equal(cards.find(c=>c.id==='c44').set,'EX Deoxys · 64/107 · Common');
const app=fs.readFileSync(new URL('./frontend/app.js',import.meta.url),'utf8');
vm.runInContext(app.slice(app.indexOf('function cardNumber'),app.indexOf('function searchable'))+'\n'+fs.readFileSync(new URL('./frontend/binder-tools.js',import.meta.url),'utf8').split('function conditionSummary')[0],ctx);
assert.equal(vm.runInContext('cards.filter(c=>!c.sold&&samePrinting(cards.find(c=>c.id==="c44"),c)).length',ctx),3);
assert.match(ctx.browsePhoto('/.netlify/functions/binder-api?resource=photo&id=abc'),/url=%2F.netlify/);
ctx.csv='Status,ErrorCode,ItemID,CustomLabel\rWarning,,123456789123,BINDR-c44\rFailure,240,,BINDR-c203\r';
let plan=vm.runInContext('planMarketplaceImport(csv,"results",cards)',ctx);assert.equal(plan.plans.length,1);assert.equal(plan.skipped,1);assert(!plan.plans[0].sold);
ctx.csv='Item number,Custom label (SKU),Sale date,Quantity\n123456789123,BINDR-c44,2026-09-18,1';
plan=vm.runInContext('planMarketplaceImport(csv,"sold",cards)',ctx);assert(plan.plans[0].sold);
ctx.csv='Item number,Custom label (SKU),Sale date,Quantity,Order status\n123456789123,BINDR-c44,2026-09-18,1,Cancelled';
assert.equal(vm.runInContext('planMarketplaceImport(csv,"sold",cards).plans.length',ctx),0);
ctx.csv='ItemID,CustomLabel,Status\n267788365781,BINDR-c44,Success';
assert.throws(()=>vm.runInContext('planMarketplaceImport(csv,"results",cards)',ctx),/Conflicting/);
let card={...cards.find(c=>c.id==='c44'),sold:false,ebayListings:[{itemId:'123456789123',status:'active',checkedAt:new Date().toISOString()}]};
assert.equal(cleanCard(card).ebayListings.length,1);
assert.throws(()=>cleanCard({...card,ebayListings:[{itemId:'javascript:alert(1)',status:'active',checkedAt:new Date().toISOString()}]}));
const password='test-key-long-enough-for-tests',saved={cards:[card],revision:'r1'};
const store={getWithMetadata:async()=>({data:saved,etag:'v1'}),setJSON:async(k,v)=>{Object.assign(saved,v);return {modified:true};}};
const handler=createHandler({seed:[],password:()=>password,getStore:({name})=>name==='binder-inventory'?store:{getWithMetadata:async()=>({data:{sessionKey:password}})}});
const body={card:{...card,sold:true},revision:'r1'};delete body.card.ebayListings;
const req=new Request('https://site.test/.netlify/functions/binder-api?resource=inventory',{method:'PUT',headers:{origin:'https://site.test',cookie:'binder_session='+sessionToken(password)},body:JSON.stringify(body)});
const response=await handler(req);assert.equal(response.status,200);assert(saved.cards[0].sold);assert.equal(saved.cards[0].ebayListings[0].itemId,'123456789123');
const unauthorized=await handler(new Request('https://site.test/.netlify/functions/binder-api?resource=inventory',{method:'PUT',headers:{origin:'https://site.test'},body:JSON.stringify(body)}));assert.equal(unauthorized.status,401);
console.log('Passed: three Magikarp copies, photo URLs, reports, cancelled orders, conflicts, field validation, link preservation, authorization.');
