'use strict';
const frameDialog=document.createElement('dialog');frameDialog.className='framing-dialog';frameDialog.setAttribute('aria-label','Adjust catalog photo framing');frameDialog.innerHTML=`<h2>Frame the card</h2><p>Drag around all four card edges. Leave a little space to inspect the corners.</p><p id="frameStatus" role="status"></p><div class="framing-grid"><section><h3>Original</h3><canvas id="frameSource"></canvas></section><section><h3>Catalog</h3><canvas id="framePreview"></canvas></section></div><label>Space around the card<input type="range" id="frameMargin" min="3" max="20" value="8"></label><button type="button" id="frameSave">Use this frame</button><button type="button" id="frameFull">Use full photo</button><button type="button" id="frameCancel">Cancel</button>`;document.body.appendChild(frameDialog);
let frameImage=null,frameBox=null,frameUrl=null,frameStart=null,framePrior=null,frameEdited=false,frameRequest=0;
const frameSource=sellerEl('frameSource'),framePreview=sellerEl('framePreview');
function selectedFrame(){return !frameEdited&&framePrior?framePrior:paddedCardFrame(frameBox,frameSource.width,frameSource.height,Number(sellerEl('frameMargin').value)/100);}
function drawSellerFrame(){if(!frameImage||!frameBox)return;const c=selectedFrame(),ctx=frameSource.getContext('2d');ctx.drawImage(frameImage,0,0,frameSource.width,frameSource.height);ctx.strokeStyle='#b9f59c';ctx.lineWidth=2;ctx.strokeRect(c.x*frameSource.width,c.y*frameSource.height,c.w*frameSource.width,c.h*frameSource.height);framePreview.width=720;framePreview.height=1000;framePreview.getContext('2d').drawImage(frameImage,c.x*frameImage.naturalWidth,c.y*frameImage.naturalHeight,c.w*frameImage.naturalWidth,c.h*frameImage.naturalHeight,0,0,720,1000);}
async function openSellerFrame(index){if(onlineBusy||sellerUploading)return;const request=++frameRequest;frameUrl=workingPhotos[index];if(!frameUrl)return;frameImage=null;frameBox=null;framePrior=workingFrames[frameUrl]||null;frameEdited=false;sellerEl('frameSave').disabled=true;sellerEl('frameMargin').value='8';sellerEl('frameStatus').textContent='Loading photo…';frameDialog.showModal();try{const img=new Image();img.src=frameUrl;await img.decode();if(request!==frameRequest||!frameDialog.open)return;frameImage=img;const scale=Math.min(1,480/img.naturalWidth,640/img.naturalHeight);frameSource.width=Math.round(img.naturalWidth*scale);frameSource.height=Math.round(img.naturalHeight*scale);const ctx=frameSource.getContext('2d');ctx.drawImage(img,0,0,frameSource.width,frameSource.height);frameBox=detectCard(ctx,frameSource.width,frameSource.height)||{x:0,y:0,w:frameSource.width,h:frameSource.height};sellerEl('frameStatus').textContent='Check every edge before applying. Original photos are unchanged.';sellerEl('frameSave').disabled=false;drawSellerFrame();}catch{sellerEl('frameStatus').textContent='Could not load this photo. Close and try again.';}}
function framePoint(e){const r=frameSource.getBoundingClientRect();return {x:Math.max(0,Math.min(frameSource.width,(e.clientX-r.left)*frameSource.width/r.width)),y:Math.max(0,Math.min(frameSource.height,(e.clientY-r.top)*frameSource.height/r.height))};}
frameSource.onpointerdown=e=>{if(!frameImage)return;frameStart=framePoint(e);frameSource.setPointerCapture(e.pointerId);};frameSource.onpointermove=e=>{if(!frameStart)return;const p=framePoint(e),w=Math.abs(p.x-frameStart.x),h=Math.abs(p.y-frameStart.y);if(w<10||h<10)return;frameEdited=true;frameBox={x:Math.min(p.x,frameStart.x),y:Math.min(p.y,frameStart.y),w,h};drawSellerFrame();};frameSource.onpointerup=frameSource.onpointercancel=()=>{frameStart=null;};sellerEl('frameMargin').oninput=()=>{frameEdited=true;drawSellerFrame();};
function finishFrame(remove=false){if(!frameUrl||!workingPhotos.includes(frameUrl))return;if(remove)delete workingFrames[frameUrl];else workingFrames[frameUrl]=selectedFrame();dirty=true;renderSellerPhotos();scheduleSellerDraft();frameDialog.close();}
sellerEl('frameSave').onclick=()=>finishFrame();sellerEl('frameFull').onclick=()=>finishFrame(true);sellerEl('frameCancel').onclick=()=>frameDialog.close();frameDialog.addEventListener('close',()=>{frameRequest++;frameStart=null;});
sellerEl('sellerPhotos').addEventListener('click',e=>{const b=e.target.closest('[data-frame]');if(b)openSellerFrame(Number(b.dataset.frame));});
