'use strict';
const sellerEl=id=>document.getElementById(id),sellerEsc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const sellerConditions=['Near Mint+','Near Mint','Near Mint-','Lightly Played+','Lightly Played','Lightly Played-','Moderately Played'];
let inventory=structuredClone(CARDS),editing=null,workingPhotos=[],workingRoles=[],workingFrames={},dirty=false;
function sellerMessage(s){sellerEl(sellerEl('sellerEditor').open?'sellerEditStatus':'sellerStatus').textContent=s;}
let sellerScope='available',sellerReturn=null,sellerScroll=0;
const originalInventory=new Map(CARDS.map(c=>[c.id,JSON.stringify(c)]));
const sellerSetName=c=>c.set.split('·')[0].trim();
const sellerMoney=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2}).format(n);
function sellerConditionClass(c){return (c.startsWith('Near Mint')?'nm':c.startsWith('Lightly')?'lp':'mp')+(c.endsWith('+')?' plus':c.endsWith('-')?' minus':'');}
function sellerMatches(){const q=sellerEl('sellerSearch').value.toLowerCase().trim().split(/\s+/).filter(Boolean);return inventory.filter(c=>c.name.trim()&&(sellerScope==='all'||(sellerScope==='sold'?c.sold:!c.sold))&&(sellerEl('sellerSetFilter').value==='all'||sellerSetName(c)===sellerEl('sellerSetFilter').value)&&(sellerEl('sellerConditionFilter').value==='all'||c.condition===sellerEl('sellerConditionFilter').value)&&q.every(w=>(c.name+' '+c.set+' '+c.id).toLowerCase().includes(w)));}
function sellerList(){
 const chosenSet=sellerEl('sellerSetFilter').value||'all';sellerEl('sellerSetFilter').innerHTML='<option value="all">All sets</option>'+[...new Set(inventory.filter(c=>c.name.trim()).map(sellerSetName))].sort().map(x=>`<option value="${sellerEsc(x)}">${sellerEsc(x)}</option>`).join('');sellerEl('sellerSetFilter').value=[...inventory.map(sellerSetName),'all'].includes(chosenSet)?chosenSet:'all';
 const filterSummary=sellerEl('sellerFilterSummary');if(filterSummary){const count=[sellerEl('sellerSetFilter').value,sellerEl('sellerConditionFilter').value].filter(v=>v!=='all').length;filterSummary.textContent=count?'Filters · '+count+' active':'Filter by set or condition';}
 const cards=sellerMatches();sellerEl('sellerResultCount').textContent=`${cards.length} listing${cards.length===1?'':'s'}`;
 sellerEl('sellerAvailableCount').textContent=inventory.filter(c=>c.name.trim()&&!c.sold).length;sellerEl('sellerSoldCount').textContent=inventory.filter(c=>c.name.trim()&&c.sold).length;
 const count=inventory.filter(c=>c.name.trim()&&originalInventory.get(c.id)!==JSON.stringify(c)).length;sellerEl('sellerDraftCount').textContent='Live binder connected';
 document.querySelectorAll('[data-seller-scope]').forEach(b=>{b.setAttribute('aria-pressed',String(b.dataset.sellerScope===sellerScope));b.classList.toggle('active',b.dataset.sellerScope===sellerScope);});
 sellerEl('sellerGrid').innerHTML=cards.length?cards.map(c=>`<article class="pocket seller-pocket${c.sold?' sold':''}"><button class="photo-open" data-edit="${sellerEsc(c.id)}" aria-label="Edit ${sellerEsc(c.name)}"><span class="pocket-image-frame ${cardFrameStyle(c)?'is-framed':''}" style="${cardFrameStyle(c)}"><img ${browseImageAttributes(c.thumb||c.photos[0])} alt="${sellerEsc(c.name)}" loading="lazy" width="260" height="347"></span><span class="photo-count">${c.photos.length} photos · Tap to edit</span></button><div class="pocket-body"><div class="card-labels"><span class="condition ${sellerConditionClass(c.condition)}">${sellerEsc(c.condition)}</span><span class="sold-label">${c.sold?'Sold':'Available'}</span>${originalInventory.get(c.id)!==JSON.stringify(c)?'<span class="seller-draft-badge">Not saved</span>':''}</div><button class="title-button" data-edit="${sellerEsc(c.id)}">${sellerEsc(c.name)}</button><div class="set-name">${sellerEsc(c.set)}<br>${sellerEsc(c.id.toUpperCase())}</div><strong class="price">${sellerMoney(c.price)}</strong><div class="seller-pocket-actions"><button data-edit="${sellerEsc(c.id)}">Edit listing</button><button class="${c.sold?'seller-restore':'seller-mark-sold'}" data-sold="${sellerEsc(c.id)}">${c.sold?'Mark available':'Mark sold'}</button></div></div></article>`).join(''):'<div class="empty"><h2>No matching listings</h2><p>Try another search or availability tab.</p><button id="sellerEmptyReset">Clear search and filters</button></div>';
 if(typeof renderMarketplace==='function')renderMarketplace();
 if(sellerEl('sellerEmptyReset'))sellerEl('sellerEmptyReset').onclick=resetSellerFilters;
}
function resetSellerFilters(){sellerEl('sellerSearch').value='';sellerEl('sellerSetFilter').value='all';sellerEl('sellerConditionFilter').value='all';sellerList();}
function markSellerSold(){sellerMessage('Sign in to save changes.');}
function openSellerEditor(id){sellerReturn=id;sellerScroll=window.scrollY;sellerEl('sellerUndo').hidden=true;sellerEl('sellerEditStatus').textContent='';loadSellerCard(id);sellerEl('sellerEditor').showModal();sellerEl('sellerForm').scrollTop=0;}
function closeSellerEditor(){if(typeof onlineBusy!=='undefined'&&onlineBusy)return false;if(dirty&&!confirm('Discard unsaved edits to this listing?'))return false;if(editing&&!editing.name.trim())inventory=inventory.filter(c=>c.id!==editing.id);dirty=false;sellerEl('sellerUpload').value='';sellerEl('sellerEditor').close();sellerList();return true;}
function renderSellerPhotos(){sellerEl('sellerPhotos').innerHTML=workingPhotos.map((p,i)=>`<div><img src="${sellerEsc(p)}" alt="Photo ${i+1}"><label>Photo ${i+1}${i===0?' · Binder cover':''}<select data-role="${i}">${['','front','back','detail'].map(r=>`<option value="${r}" ${workingRoles[i]===r?'selected':''}>${r||'Unlabeled'}</option>`).join('')}</select></label><button type="button" data-up="${i}" ${i===0?'disabled':''}>Move earlier</button><button type="button" data-frame="${i}">${workingFrames[p]?'Adjust framing':'Frame photo'}</button><button type="button" data-delete="${i}">Remove photo</button></div>`).join('');}
function loadSellerCard(id){const c=inventory.find(x=>x.id===id);if(!c)return;editing=c;dirty=false;workingPhotos=[...c.photos];workingFrames=structuredClone(c.photoFrames||{});workingRoles=[...(c.photoRoles||c.photos.map(()=>''))];sellerEl('editingTitle').textContent='Editing '+c.id.toUpperCase();sellerEl('sellerName').value=c.name;sellerEl('sellerSet').value=c.set;sellerEl('sellerPrice').value=c.price||'';sellerEl('sellerCondition').value=c.condition;sellerEl('sellerAvailability').value=c.sold?'sold':'available';sellerEl('sellerDescription').value=c.description||'';renderSellerPhotos();}
sellerEl('sellerCondition').innerHTML=sellerConditions.map(c=>`<option>${c}</option>`).join('');
sellerEl('sellerConditionFilter').innerHTML='<option value="all">Any condition</option>'+sellerConditions.map(c=>`<option>${c}</option>`).join('');
sellerEl('sellerSearch').oninput=sellerList;['sellerSetFilter','sellerConditionFilter'].forEach(id=>sellerEl(id).onchange=sellerList);
sellerEl('sellerReset').onclick=resetSellerFilters;
document.querySelectorAll('[data-seller-scope]').forEach(b=>b.onclick=()=>{sellerScope=b.dataset.sellerScope;sellerList();});
sellerEl('sellerGrid').onclick=e=>{const b=e.target.closest('button');if(b?.dataset.edit)openSellerEditor(b.dataset.edit);if(b?.dataset.sold)markSellerSold(b.dataset.sold);};
sellerEl('closeSellerEditor').onclick=closeSellerEditor;
sellerEl('sellerEditor').addEventListener('cancel',e=>{e.preventDefault();closeSellerEditor();});
sellerEl('sellerEditor').addEventListener('close',()=>{const b=Array.from(sellerEl('sellerGrid').querySelectorAll('[data-edit]')).find(b=>b.dataset.edit===sellerReturn);(b||sellerEl('sellerSearch')).focus({preventScroll:true});window.scrollTo({top:sellerScroll,behavior:'instant'});});
sellerList();
sellerEl('sellerForm').addEventListener('input',()=>{dirty=true;});
sellerEl('sellerPhotos').addEventListener('change',e=>{if(e.target.dataset.role!==undefined){workingRoles[Number(e.target.dataset.role)]=e.target.value;dirty=true;}});
sellerEl('sellerPhotos').addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.up!==undefined){const i=Number(b.dataset.up);[workingPhotos[i-1],workingPhotos[i]]=[workingPhotos[i],workingPhotos[i-1]];[workingRoles[i-1],workingRoles[i]]=[workingRoles[i],workingRoles[i-1]];}if(b.dataset.delete!==undefined){workingPhotos.splice(Number(b.dataset.delete),1);workingRoles.splice(Number(b.dataset.delete),1);}dirty=true;renderSellerPhotos();});
sellerEl('newListing').onclick=()=>{const id='c'+(Math.max(0,...inventory.map(c=>Number(c.id.slice(1))||0))+1);inventory.push({id,name:'',set:'',price:0,condition:'Near Mint',sold:false,description:'',photos:[],thumb:''});openSellerEditor(id);dirty=true;sellerEl('sellerName').focus();};
sellerEl('sellerForm').onsubmit=e=>{e.preventDefault();sellerMessage('Sign in to save changes.');};
sellerEl('exportInventory').onclick=()=>{if(dirty){sellerMessage('Save the current listing before exporting.');return;}if(inventory.some(c=>!c.name.trim()||!c.set.trim()||!c.photos.length||!(c.price>0))){sellerMessage('Complete all new listings before exporting.');return;}const blob=new Blob(['// Inventory exported from The Binder seller workspace.\nconst CARDS = '+JSON.stringify(inventory,null,2)+';\n'],{type:'text/javascript'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='cards.js';a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);sellerMessage('Inventory backup downloaded. Live updates are already stored online.');};
window.addEventListener('beforeunload',e=>{if(dirty||(typeof onlineBusy!=='undefined'&&onlineBusy)){e.preventDefault();e.returnValue='';}});

