import test from 'node:test';
import {scryptSync} from 'node:crypto';
import assert from 'node:assert/strict';
import {createHandler,authorized,sessionToken,cleanCard} from '../server/core.mjs';
const password='test-password-only-very-long';
const card={id:'c1',name:'Pikachu',set:'Base Set · 58/102',price:50,condition:'Near Mint',sold:false,photos:['images/full/c1_1.jpg'],thumb:'images/grid/c1.jpg',description:'Example',photoRoles:['front']};
function environment(bootstrap=null){const stores=new Map();let serial=0;const getStore=({name})=>{if(!stores.has(name))stores.set(name,new Map());const data=stores.get(name);return {async getWithMetadata(key){return data.has(key)?structuredClone(data.get(key)):null;},async setJSON(key,value,options={}){return this.set(key,value,options);},async set(key,value,options={}){const old=data.get(key);if(options.onlyIfNew&&old||options.onlyIfMatch&&old?.etag!==options.onlyIfMatch)return {modified:false};const etag=String(++serial);data.set(key,{data:structuredClone(value),etag,metadata:options.metadata||{}});return {modified:true,etag};}};};return createHandler({getStore,seed:[card],bootstrap,password:()=>password});}
function req(resource,method='GET',body,token,origin='https://binder.test'){return new Request('https://binder.test/.netlify/functions/binder-api?resource='+resource,{method,headers:{...(method!=='GET'?{origin}:{}),...(token?{cookie:'binder_session='+token}:{}),'Content-Type':'application/json'},...(body!==undefined?{body:JSON.stringify(body)}:{})});}
const token=sessionToken(password);
test('session requires correct signature and expiry',()=>{assert(authorized(req('session','GET',undefined,token),password));assert(!authorized(req('session','GET',undefined,token+'x'),password));assert(!authorized(req('session','GET',undefined,sessionToken(password,0)),password));assert(!authorized(req('session','GET',undefined,token),'changed-password-value'));});
test('public reads seed; unauthenticated mutation fails',async()=>{const app=environment();assert.equal((await (await app(req('inventory'))).json()).cards.length,1);assert.equal((await app(req('inventory','PUT',{card}))).status,401);});
test('wrong password rejected and login cookie protected',async()=>{const app=environment();assert.equal((await app(req('session','POST',{password:'wrong'}),{ip:'one'})).status,401);const r=await app(req('session','POST',{password}),{ip:'one'});assert.equal(r.status,200);assert.match(r.headers.get('set-cookie'),/HttpOnly; Secure; SameSite=Strict/);});
test('cross-origin write and login rejected',async()=>{const app=environment();assert.equal((await app(req('session','POST',{password},null,'https://other.test'))).status,403);assert.equal((await app(req('inventory','PUT',{card},token,'https://other.test'))).status,403);});
test('missing password fails closed',async()=>{const app=createHandler({getStore(){throw Error()},seed:[card],password:()=>''});assert.equal((await app(req('session','POST',{password}))).status,503);});
test('sold mutation appears on public read',async()=>{const app=environment(),initial=await (await app(req('inventory'))).json();const r=await app(req('inventory','PUT',{revision:initial.revision,card:{...card,sold:true}},token));assert.equal(r.status,200);assert.equal((await (await app(req('inventory'))).json()).cards[0].sold,true);});
test('stale tab cannot overwrite newer save',async()=>{const app=environment(),initial=await (await app(req('inventory'))).json();await app(req('inventory','PUT',{revision:initial.revision,card:{...card,sold:true}},token));assert.equal((await app(req('inventory','PUT',{revision:initial.revision,card},token))).status,409);});
test('concurrent first writes have one winner',async()=>{const app=environment(),initial=await (await app(req('inventory'))).json();const r=await Promise.all([app(req('inventory','PUT',{revision:initial.revision,card:{...card,price:60}},token)),app(req('inventory','PUT',{revision:initial.revision,card:{...card,price:70}},token))]);assert.deepEqual(r.map(x=>x.status).sort(),[200,409]);});
test('new card persists',async()=>{const app=environment(),initial=await (await app(req('inventory'))).json();assert.equal((await app(req('inventory','PUT',{revision:initial.revision,card:{...card,id:'c2'}},token))).status,200);assert.equal((await (await app(req('inventory'))).json()).cards.length,2);});
test('invalid fields and unsafe images rejected',()=>{for(const patch of [{price:-1},{name:''},{id:'<script>'},{condition:'invented'},{photos:['https://other.test/a.jpg']},{thumb:'images/../secret.jpg'},{photoRoles:['front','front']}])assert.throws(()=>cleanCard({...card,...patch}));});
test('login attempt limit persists across requests',async()=>{const app=environment();for(let i=0;i<10;i++)assert.equal((await app(req('session','POST',{password:'wrong'}),{ip:'one'})).status,401);assert.equal((await app(req('session','POST',{password}),{ip:'one'})).status,429);assert.equal((await app(req('session','POST',{password}),{ip:'two'})).status,200);});
test('photo upload checks authentication and image signature',async()=>{const app=environment();const make=(auth,bytes)=>new Request('https://binder.test/.netlify/functions/binder-api?resource=photo',{method:'POST',headers:{origin:'https://binder.test','Content-Type':'image/jpeg',...(auth?{cookie:'binder_session='+token}:{})},body:bytes});assert.equal((await app(make(false,new Uint8Array([255,216,255])))).status,401);assert.equal((await app(make(true,new Uint8Array([0,0,0])))).status,400);const r=await app(make(true,new Uint8Array([255,216,255,217])));assert.equal(r.status,200);const {url}=await r.json();const photo=await app(new Request('https://binder.test'+url));assert.equal(photo.headers.get('content-type'),'image/jpeg');assert.equal((await photo.arrayBuffer()).byteLength,4);});
test('oversized photo rejected',async()=>{const app=environment(),r=await app(new Request('https://binder.test/.netlify/functions/binder-api?resource=photo',{method:'POST',headers:{origin:'https://binder.test','Content-Type':'image/jpeg',cookie:'binder_session='+token},body:new Uint8Array(3*1024*1024+1)}));assert.equal(r.status,413);});
test('logout clears cookie',async()=>{const r=await environment()(req('session','DELETE',undefined,token));assert.match(r.headers.get('set-cookie'),/Max-Age=0/);});
test('storage errors do not report success',async()=>{const app=createHandler({getStore(){throw Error('storage offline')},seed:[card],password:()=>password});assert.equal((await app(req('inventory'))).status,503);});
test('first visit reports setup state without exposing owner key',async()=>{const r=await environment()(req('session'));const data=await r.json();assert.equal(data.setupRequired,true);assert.equal(data.ownerKeyConfigured,true);assert(!JSON.stringify(data).includes(password));});
test('owner creates password on page and signs in with new password',async()=>{const app=environment(),newPassword='my-new-seller-password-123';let r=await app(req('session','POST',{action:'setup',ownerKey:password,password:newPassword}),{ip:'one'});assert.equal(r.status,200);const cookieValue=r.headers.get('set-cookie').split(';')[0];r=await app(new Request('https://binder.test/.netlify/functions/binder-api?resource=session',{headers:{cookie:cookieValue}}));assert.deepEqual(await r.json(),{authenticated:true,setupRequired:false,ownerKeyConfigured:true});assert.equal((await app(req('session','POST',{password:newPassword}),{ip:'one'})).status,200);assert.equal((await app(req('session','POST',{password}),{ip:'one'})).status,401);});
test('unknown visitor cannot claim owner account',async()=>{const app=environment();assert.equal((await app(req('session','POST',{action:'setup',ownerKey:'wrong',password:'a-new-password-with-length'}),{ip:'one'})).status,401);assert.equal((await (await app(req('session'))).json()).setupRequired,true);});
test('setup cannot replace an existing owner account',async()=>{const app=environment();const body={action:'setup',ownerKey:password,password:'a-new-password-with-length'};assert.equal((await app(req('session','POST',body),{ip:'one'})).status,200);assert.equal((await app(req('session','POST',body),{ip:'one'})).status,409);});

const boot={email:'owner@example.test',salt:'test-salt',passwordHash:scryptSync('temporary-test-password','test-salt',64).toString('hex'),rateKey:'test-rate-key-not-production'};
const credentials={email:boot.email,password:'temporary-test-password'};
test('private beta denies registration, incorrect email, key login and premature writes',async()=>{const app=environment(boot);assert.equal((await app(req('session','POST',{action:'setup',ownerKey:password,password}))).status,403);assert.equal((await app(req('session','POST',{...credentials,email:'other@example.test'}))).status,401);assert.equal((await app(req('session','POST',{email:boot.email,password}))).status,401);assert.equal((await app(req('inventory','PUT',{card},sessionToken(boot.rateKey)))).status,401);const r=await app(req('session','POST',credentials));assert.deepEqual(await r.json(),{changeRequired:true});assert.equal(r.headers.get('set-cookie'),null);});
test('private beta activation requires replacement password and disables temporary password',async()=>{const app=environment(boot);assert.equal((await app(req('session','POST',{...credentials,action:'activate',newPassword:'short'}))).status,400);const newPassword='a-private-replacement-password';const r=await app(req('session','POST',{...credentials,action:'activate',newPassword}));assert.equal(r.status,200);assert(r.headers.get('set-cookie'));assert.equal((await app(req('session','POST',credentials))).status,401);assert.equal((await app(req('session','POST',{email:boot.email,password:newPassword}))).status,200);const auth=r.headers.get('set-cookie').split(';')[0].split('=')[1];const initial=await (await app(req('inventory'))).json();assert.equal((await app(req('inventory','PUT',{card:{...card,sold:true},revision:initial.revision},auth))).status,200);assert.equal((await (await app(req('inventory'))).json()).cards[0].sold,true);});
test('private beta activation is atomic',async()=>{const app=environment(boot);const results=await Promise.all([1,2].map(n=>app(req('session','POST',{...credentials,action:'activate',newPassword:'replacement-password-'+n}))));assert.deepEqual(results.map(r=>r.status).sort(),[200,409]);});
test('delete requires authorization and current revision',async()=>{const app=environment(),initial=await (await app(req('inventory'))).json();assert.equal((await app(req('inventory','DELETE',{id:'c1',revision:initial.revision}))).status,401);assert.equal((await app(req('inventory','DELETE',{id:'c1',revision:'stale'},token))).status,409);assert.equal((await (await app(req('inventory'))).json()).cards.length,1);});
test('deletion removes listing entirely and persists empty inventory',async()=>{const app=environment(),initial=await (await app(req('inventory'))).json();const r=await app(req('inventory','DELETE',{id:'c1',revision:initial.revision},token));assert.equal(r.status,200);assert.deepEqual((await r.json()).cards,[]);assert.deepEqual((await (await app(req('inventory'))).json()).cards,[]);});
test('concurrent delete and edit cannot overwrite each other',async()=>{const app=environment(),initial=await (await app(req('inventory'))).json();const results=await Promise.all([app(req('inventory','DELETE',{id:'c1',revision:initial.revision},token)),app(req('inventory','PUT',{card:{...card,price:60},revision:initial.revision},token))]);assert.deepEqual(results.map(r=>r.status).sort(),[200,409]);});
test('delete rejects missing and invalid IDs',async()=>{const app=environment(),initial=await (await app(req('inventory'))).json();assert.equal((await app(req('inventory','DELETE',{id:'c999',revision:initial.revision},token))).status,404);assert.equal((await app(req('inventory','DELETE',null,token))).status,400);});
