import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFileSync} from 'node:fs';
const prepContext={Uint8Array,Error};vm.createContext(prepContext);vm.runInContext(readFileSync('frontend/photo-preparation.js','utf8'),prepContext);const prep=prepContext.BinderPhotoPreparation;
test('photo detection uses bytes even with missing or wrong phone MIME',async()=>{const jpeg=new File([new Uint8Array([255,216,255,224])],'photo.heic',{type:''});assert.equal(await prep.photoKind(jpeg),'image/jpeg');const heic=new File([new Uint8Array([0,0,0,24]),'ftypheic','0000'],'photo',{type:''});assert.equal(await prep.photoKind(heic),'image/heic');await assert.rejects(prep.photoKind(new File(['bad'],'fake.jpg',{type:'image/jpeg'})));});
test('preparation retains full aspect ratio, never enlarges small photos',()=>{const fit=prep.fitPhoto(4032,3024);assert.equal(fit.width,3072);assert.equal(fit.height,2304);assert.equal(prep.fitPhoto(900,1200).width,900);assert.equal(prep.fitPhoto(3024,4032).height,3072);});
test('encoding fits limit and releases its canvas',async()=>{let canvas,draw;const output=await prep.encodePhoto({},4032,3024,()=>canvas={getContext:()=>({fillRect(){},drawImage(...args){draw=args;}}),toBlob(cb,type,quality){cb(new Blob([new Uint8Array(quality>.9?4*1024*1024:2*1024*1024)],{type}));}});assert.equal(output.quality,.9);assert(output.blob.size<=prep.MAX_BYTES);assert.deepEqual(draw.slice(1),[0,0,3072,2304]);assert.equal(canvas.width,1);assert.equal(canvas.height,1);});
function harness(){const nodes={};const el=id=>nodes[id]??={value:'',innerHTML:'',textContent:'',disabled:false,hidden:false,addEventListener(){}};const calls=[],prepared=[],failNames=new Set(['bad.jpg']);let confirmResult=true;const c={File,Blob,Response,Error,console,Set,Map,Number,Array,Promise,clearTimeout,setTimeout,onlineBusy:false,sellerSignedIn:true,workingFrames:{},workingPhotos:[],workingRoles:[],dirty:false,loadSellerCard(){},sellerEl:el,sellerEsc:s=>String(s).replaceAll('<','&lt;'),setOnlineBusy(v){c.onlineBusy=v;},renderSellerPhotos(){},sellerMessage(m){el('message').textContent=m;},confirm:()=>confirmResult,};vm.createContext(c);vm.runInContext(readFileSync('frontend/phone-photos.js','utf8'),c);c.prepareSellerPhoto=async file=>{prepared.push(file.name);return {blob:file,width:3024,height:4032,original:true};};c.uploadSellerPhoto=async(blob,onProgress)=>{const name=blob.name;calls.push(name);onProgress(60);if(failNames.has(name))throw Error('Connection lost');return {url:'images/'+name};};return {c,el,calls,prepared,failNames,run:s=>vm.runInContext(s,c),confirm:v=>confirmResult=v};}
test('mixed batch keeps successful photos; retry only sends failed file',async()=>{const h=harness();h.run("sellerUploadQueue=['good.jpg','bad.jpg','last.jpg'].map((name,id)=>({id:id+1,name,file:new File(['abc'],name),state:'queued'}))");await h.run('processSellerUploads()');assert.deepEqual(h.c.workingPhotos,['images/good.jpg','images/last.jpg']);assert.equal(h.c.onlineBusy,false);assert.match(h.el('uploadSummary').textContent,/1 need attention/);h.failNames.clear();h.run("sellerUploadQueue.filter(x=>x.state==='failed').forEach(x=>x.state='queued')");await h.run('processSellerUploads()');assert.deepEqual(h.calls,['good.jpg','bad.jpg','last.jpg','bad.jpg']);assert.deepEqual(h.prepared,['good.jpg','bad.jpg','last.jpg']);assert.equal(h.c.workingPhotos.length,3);assert.equal(h.run("sellerUploadQueue.every(x=>x.file===null&&x.prepared===null)"),true);});
test('full listing rejects retry without uploading or removing existing photos',async()=>{const h=harness();h.c.workingPhotos=Array.from({length:20},(_,i)=>'images/'+i);h.run("sellerUploadQueue=[{id:1,name:'extra.jpg',file:new File(['a'],'extra.jpg'),state:'queued'}]");await h.run('processSellerUploads()');assert.equal(h.calls.length,0);assert.equal(h.c.workingPhotos.length,20);assert.match(h.run('sellerUploadQueue[0].message'),/20 photos/);});
test('partial batch save asks before leaving failed files out and reset clears queue',async()=>{const h=harness();h.run("sellerUploadQueue=[{id:1,state:'failed',message:'error',name:'bad.jpg'}]");h.confirm(false);assert.equal(h.run('confirmPartialUploadSave()'),false);h.confirm(true);assert.equal(h.run('confirmPartialUploadSave()'),true);h.run("loadSellerCard('c2')");assert.equal(h.run('sellerUploadQueue.length'),0);});
test('expired session preserves queued files for retry',async()=>{const h=harness();h.c.sellerSignedIn=false;h.run("sellerUploadQueue=[{id:1,name:'good.jpg',file:new File(['a'],'good.jpg'),state:'queued'}]");await h.run('processSellerUploads()');assert.equal(h.calls.length,0);assert.equal(h.run('sellerUploadQueue[0].state'),'queued');assert.match(h.el('message').textContent,/Sign in again/);});
test('uploads get a ticket, post the thumbnail and photo to storage, then confirm',async()=>{const posts=[],api=[];const c={FormData:class{constructor(){this.parts=[];}append(k,v){this.parts.push([k,v]);}},XMLHttpRequest:class{open(m,u){this.url=u;}send(form){posts.push({url:this.url,fields:Object.fromEntries(form.parts.filter(([k])=>k!=='file')),file:form.parts.at(-1)[1]});this.upload.onprogress({lengthComputable:true,loaded:5,total:10});this.status=204;this.onload();}constructor(){this.upload={};}},document:{createElement:()=>({getContext:()=>({fillRect(){},drawImage(){}}),toBlob:cb=>cb(new Blob(['t'],{type:'image/jpeg'}))})},BinderPhotoPreparation:{fitPhoto:(w,h,m)=>({width:m,height:m})},sellerEl:()=>({addEventListener(){},value:''}),loadSellerCard(){},URL,URLSearchParams,setTimeout,clearTimeout,File,Set,Map,Number,Array,Blob,Error,Promise,Object,Math,JSON,console,
 sellerAPI:async(resource,opts)=>{api.push({resource,body:JSON.parse(opts.body)});return resource==='photos/uploads'?{key:'dev/photos/k.jpg',upload:{url:'https://s3.test/',fields:{key:'dev/photos/k.jpg'}},thumbUpload:{url:'https://s3.test/',fields:{key:'dev/photos/k_thumb.jpg'}}}:{url:'https://s3.test/dev/photos/k.jpg'};}};
 vm.createContext(c);vm.runInContext(readFileSync('frontend/phone-photos.js','utf8'),c);c.readPhotoImage=async()=>({width:4000,height:3000,source:{},close(){}});const progress=[];const photo=new Blob(['photo-bytes'],{type:'image/png'});
 const result=await c.uploadSellerPhoto(photo,p=>progress.push(p));
 assert.deepEqual(api.map(a=>a.resource),['photos/uploads','photos/confirm']);assert.deepEqual(api[0].body,{contentType:'image/png',bytes:photo.size,thumbBytes:1});assert.deepEqual(api[1].body,{key:'dev/photos/k.jpg'});
 assert.deepEqual(posts.map(p=>p.fields.key),['dev/photos/k_thumb.jpg','dev/photos/k.jpg']);assert.equal(posts[1].file,photo);assert.equal(result.url,'https://s3.test/dev/photos/k.jpg');assert(progress.includes(50)&&progress.at(-1)===99);});
