import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { createHandler, sessionToken } from '../server/core.mjs';
import { parsePokemonCardText } from '../server/scan/ocr-parse.mjs';
import { ratio, tokenSortRatio } from '../server/scan/fuzz.mjs';
import { matchCard, localIdVariants } from '../server/scan/match.mjs';
import { createScanner, listingFields } from '../server/scan/index.mjs';

// Expected values were generated by leftovers.gg's Python parser and rapidfuzz 3.6.1.
const reference = JSON.parse(readFileSync(new URL('./fixtures/scanner-python-reference.json', import.meta.url), 'utf8'));

test('OCR parsing matches the leftovers.gg Python parser', () => {
 for (const { text, expected } of reference.parse) assert.deepEqual(parsePokemonCardText(text), expected, JSON.stringify(text));
});

test('fuzzy scores match rapidfuzz exactly', () => {
 for (const c of reference.fuzz) {
  assert.equal(ratio(c.a, c.b), c.ratio, `ratio ${c.a} | ${c.b}`);
  assert.equal(tokenSortRatio(c.a, c.b), c.token_sort_ratio, `token_sort_ratio ${c.a} | ${c.b}`);
 }
});

test('local id variants cover padded, No. and TG numbers', () => {
 assert.deepEqual(localIdVariants('006/091'), ['006', '6']);
 assert.deepEqual(localIdVariants('No.150'), ['150']);
 assert.deepEqual(localIdVariants('TG15/TG30'), ['TG15']);
 assert.deepEqual(localIdVariants('12/101'), ['12']);
});

// In-memory catalog implementing the same queries as catalog.mjs.
function fakeCatalog(rows) {
 const inLang = (r, lang) => !lang || r.language_code === lang;
 const like = (value, text) => (value || '').normalize('NFD').replace(/[̀-ͯ]/g, '').toLowerCase().includes(text.toLowerCase());
 return {
  byPrintedNumber: async (n, lang) => rows.filter(r => inLang(r, lang) && (r.printed_number || '').toLowerCase() === n.toLowerCase()),
  byNumbers: async (v, lang, limit = Infinity) => rows.filter(r => inLang(r, lang) && v.includes(r.number)).slice(0, limit),
  byNameLike: async (t, lang, limit) => rows.filter(r => inLang(r, lang) && (like(r.name, t) || like(r.en_name, t))).slice(0, limit),
  byArtistLike: async (t, lang, limit) => rows.filter(r => inLang(r, lang) && like(r.artist, t)).slice(0, limit),
 };
}
const card = (id, fields) => ({ id, name: 'Charizard', en_name: null, number: '4', printed_number: '4/102', hp: '120', artist: 'Mitsuhiro Arita', rarity: 'Rare Holo', language_code: 'EN', images: [{ small: `https://img.test/${id}/small` }], set_name: 'Base', set_name_en: null, ...fields });
const ocr = fields => ({ name: 'Charizard', name_candidates: ['Charizard'], set_number: '4/102', hp: 120, illustrator: 'Mitsuhiro Arita', language_code: 'EN', ...fields });

test('a unique printed number matches directly', async () => {
 const m = await matchCard(ocr({}), fakeCatalog([card('a'), card('b', { printed_number: '5/102', number: '5' })]));
 assert.equal(m.card.id, 'a');
 assert.equal(m.method, 'v3_printed_number');
 assert.equal(m.confidence, 0.99);
});

test('shared printed numbers are separated by HP, then artist', async () => {
 const byHp = await matchCard(ocr({}), fakeCatalog([card('a'), card('b', { hp: '100' })]));
 assert.equal(byHp.card.id, 'a');
 assert.equal(byHp.method, 'v3_printed_number_hp_elim');
 const byArtist = await matchCard(ocr({ hp: null }), fakeCatalog([card('a'), card('b', { artist: 'Ken Sugimori' })]));
 assert.equal(byArtist.card.id, 'a');
 assert.equal(byArtist.method, 'v3_printed_number_artist');
});

test('identical candidates are returned for the seller to choose', async () => {
 const m = await matchCard(ocr({}), fakeCatalog([card('a', { set_name: 'Base' }), card('b', { set_name: 'Base Set 2' })]));
 assert.equal(m.ambiguous, true);
 assert.deepEqual(m.candidates.map(r => r.id), ['a', 'b']);
});

test('without a number the best name wins, and weak names do not match', async () => {
 const rows = [card('a'), card('b', { name: 'Charmander', printed_number: '46/102', number: '46', hp: '50', artist: 'Ken Sugimori' })];
 const m = await matchCard(ocr({ set_number: null, illustrator: null, hp: null }), fakeCatalog(rows));
 assert.equal(m.card.id, 'a');
 assert.equal(m.method, 'v3_name_primary');
 assert.equal(await matchCard(ocr({ set_number: null, name: 'Blastoise', name_candidates: ['Blastoise'], illustrator: null }), fakeCatalog(rows)), null);
});

test('listing fields use Bindr set format and label Japanese cards', () => {
 assert.deepEqual(listingFields(card('a')), { id: 'a', name: 'Charizard', set: 'Base · 4/102 · Rare Holo', catalog_name: 'Charizard', image_url: 'https://img.test/a/small', language_code: 'EN' });
 const ja = listingFields(card('j', { name: 'リザードン', en_name: 'Charizard', language_code: 'JA', set_name: '拡張パック', rarity: null, printed_number: null, number: '6' }));
 assert.equal(ja.name, 'Charizard (Japanese)');
 assert.equal(ja.set, '拡張パック · 6');
 assert.equal(listingFields(card('n', { rarity: 'None' })).set, 'Base · 4/102');
});

test('scanner reports matched, ambiguous, no-match and no-text results', async () => {
 const catalog = fakeCatalog([card('a'), card('b', { printed_number: '2/102', number: '2', name: 'Blastoise' }), card('c', { printed_number: '2/102', number: '2', name: 'Blastoise' })]);
 const scanWith = text => createScanner({ detectText: async () => text, catalog })(Buffer.from([255, 216, 255]));
 const hit = await scanWith('Charizard\n120 HP\nIllus. Mitsuhiro Arita\n4/102');
 assert.equal(hit.status, 'matched');
 assert.equal(hit.card.set, 'Base · 4/102 · Rare Holo');
 assert.equal(hit.ocr.set_number, '4/102');
 assert.equal((await scanWith('Blastoise\n2/102')).status, 'ambiguous');
 assert.equal((await scanWith('Mew\n999/999')).status, 'no_match');
 assert.equal((await scanWith('')).status, 'no_text');
});

// ---- binder-api ?resource=scan ----
const password = 'test-password-only-very-long';
const emptyStore = () => ({ async getWithMetadata() { return null; } });
const jpeg = new Uint8Array([255, 216, 255, 217]);
const scanRequest = ({ auth = true, type = 'image/jpeg', body = jpeg, origin = 'https://binder.test' } = {}) => new Request('https://binder.test/.netlify/functions/binder-api?resource=scan', {
 method: 'POST', body, headers: { origin, 'Content-Type': type, ...(auth ? { cookie: 'binder_session=' + sessionToken(password) } : {}) },
});
const app = scan => createHandler({ getStore: emptyStore, seed: [], password: () => password, scan });

test('scan route requires sign-in, same origin and a JPEG', async () => {
 let calls = 0;
 const handler = app(async () => { calls++; return { status: 'no_text' }; });
 assert.equal((await handler(scanRequest({ auth: false }))).status, 401);
 assert.equal((await handler(scanRequest({ origin: 'https://other.test' }))).status, 403);
 assert.equal((await handler(scanRequest({ type: 'image/png' }))).status, 400);
 assert.equal((await handler(scanRequest({ body: new Uint8Array([0, 0, 0]) }))).status, 400);
 assert.equal((await handler(scanRequest({ body: new Uint8Array(4 * 1024 * 1024 + 1) }))).status, 413);
 assert.equal(calls, 0);
 const ok = await handler(scanRequest());
 assert.equal(ok.status, 200);
 assert.deepEqual(await ok.json(), { status: 'no_text' });
});

test('scan failures are reported without claiming a storage outage', async () => {
 const original = console.error;
 console.error = () => {};
 try {
  const broken = await app(async () => { throw Error('vision down'); })(scanRequest());
  assert.equal(broken.status, 502);
  assert.match((await broken.json()).error, /scanning is unavailable/);
  const unconfigured = await app(async () => { throw Object.assign(Error('Card scanning is not set up yet.'), { status: 503 }); })(scanRequest());
  assert.equal(unconfigured.status, 503);
  assert.equal((await unconfigured.json()).error, 'Card scanning is not set up yet.');
  assert.equal((await app(null)(scanRequest())).status, 503);
 } finally { console.error = original; }
});
