import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFileSync} from 'node:fs';
const card={id:'c1',name:'Pikachu',set:'Base · 58/102',price:50,condition:'Near Mint',sold:false,photos:['images/a.jpg'],thumb:'images/a.jpg',description:''};
function harness(){let server={cards:[structuredClone(card)],revision:'one'},fail=false;const nodes={};const node=id=>nodes[id]??={value:['sellerSetFilter','sellerConditionFilter'].includes(id)?'all':'',dataset:{},hidden:false,open:false,disabled:false,innerHTML:'',textContent:'',classList:{toggle(){}},setAttribute(){},addEventListener(){},querySelectorAll:()=>[],focus(){},showModal(){this.open=true},close(){this.open=false},appendChild(){}};const ctx={sellerAuth:{accessToken:async()=>'test-token',signIn:async()=>{},signOut:async()=>{}},URLSearchParams,CARDS:[structuredClone(card)],structuredClone,Intl,console,AbortSignal,confirm:()=>true,window:{scrollY:0,addEventListener(){},scrollTo(){}},document:{addEventListener(){},getElementById:node,querySelectorAll:()=>[],body:{insertBefore(){}}},location:{reload(){}},fetch:async(url,opts={})=>{if(url.includes('session'))return new Response(JSON.stringify({authenticated:true}));if(opts.method==='PUT'){if(fail)return new Response(JSON.stringify({error:'Offline'}),{status:503});const b=JSON.parse(opts.body);server={cards:[b.card],revision:'two'};}return new Response(JSON.stringify(server));}};vm.createContext(ctx);vm.runInContext(readFileSync('frontend/helpers.js','utf8')+readFileSync('frontend/card-framing.js','utf8')+readFileSync('frontend/seller.js','utf8')+readFileSync('frontend/live-seller.js','utf8'),ctx);return {ctx,node,fail:()=>fail=true,server:()=>server,run:s=>vm.runInContext(s,ctx)};}
test('seller sold button saves to API before updating local inventory',async()=>{const h=harness();await h.run('loadOnlineSeller()');h.run('sellerSignedIn=true');await h.run("markSellerSold('c1')");assert.equal(h.server().cards[0].sold,true);assert.equal(h.run('inventory[0].sold'),true);assert.match(h.node('sellerStatus').textContent,/live binder/);await h.node('sellerUndo').onclick();assert.equal(h.server().cards[0].sold,false);});
test('failed save does not pretend card is sold',async()=>{const h=harness();await h.run('loadOnlineSeller()');h.run('sellerSignedIn=true');h.fail();await h.run("markSellerSold('c1')");assert.equal(h.run('inventory[0].sold'),false);assert.match(h.node('sellerStatus').textContent,/not been changed/);});
test('editing price saves and closes only after API confirms',async()=>{const h=harness();await h.run('loadOnlineSeller()');h.run("sellerSignedIn=true;openSellerEditor('c1')");h.node('sellerPrice').value='80';await h.node('sellerForm').onsubmit({preventDefault(){}});assert.equal(h.server().cards[0].price,80);assert.equal(h.node('sellerEditor').open,false);});
test('API requests carry the Supabase access token',async()=>{const h=harness();const seen=[];h.ctx.fetch=async(url,opts={})=>{seen.push({url,auth:opts.headers?.Authorization});return new Response(JSON.stringify(h.server()));};await h.run('loadOnlineSeller()');assert.equal(seen.find(x=>x.url==='/api/v1/inventory')?.auth,'Bearer test-token');assert(seen.every(x=>x.auth==='Bearer test-token'));});
test('signing in with a non-seller account signs straight back out',async()=>{const h=harness();let signedOut=false;h.ctx.sellerAuth.signOut=async()=>{signedOut=true;};h.ctx.fetch=async url=>url.includes('session')?new Response(JSON.stringify({detail:"This account can't manage the binder."}),{status:403}):new Response(JSON.stringify(h.server()));h.node('sellerEmail').value='someone@example.com';await h.node('loginForm').onsubmit({preventDefault(){}});assert.equal(signedOut,true);assert.equal(h.run('sellerSignedIn'),false);assert.equal(h.node('loginStatus').textContent,"This account can't manage the binder.");});
test('wrong password shows the sign-in error without calling the API',async()=>{const h=harness();let calls=0;h.ctx.sellerAuth.signIn=async()=>{throw Error('Incorrect email or password.');};h.ctx.fetch=async()=>{calls++;return new Response('{}');};await h.node('loginForm').onsubmit({preventDefault(){}});assert.equal(calls,0);assert.equal(h.node('loginStatus').textContent,'Incorrect email or password.');});
