// Pokémon card OCR text parsing — a port of leftovers.gg backend/app/services/ocr.py
// (_parse_pokemon_card_text and helpers). Keep the two in step: tests/fixtures/ocr-parse.json
// holds outputs generated by the Python original.

// Python's \b is Unicode-aware (Japanese characters count as word characters); JS's is not.
const WB = '(?:(?<![\\p{L}\\p{N}_])(?=[\\p{L}\\p{N}_])|(?<=[\\p{L}\\p{N}_])(?![\\p{L}\\p{N}_]))';

// Lines that are never the card name when they appear alone: stage markers, HP values,
// bare numbers, trainer/energy headers, Japanese structural labels and "No.084" lines.
const NON_NAME = new RegExp(
 '^(STAGE(?:\\s*\\d+|\\s*I{1,3}|T)?|BASIC|V\\s*MAX|HP\\s*\\d+|\\d+\\s*HP|\\d+|TRAINER|ENERGY'
 + '|\\S{0,4}進化:?'
 + '|\\d*進\\S*'
 + '|たね|にげる|弱点|抵抗力|特性|ポケパワー|ポケボディー'
 + '|No\\.\\s*\\d+)$', 'iu');

// Stage printed on the same line as the name: "BASIC Pikachu", "STAGE 1 Raichu".
const INLINE_PREFIX = /^(?:BASIC|STAGE(?:\s*\d+|\s*I{1,3}|T)?)\s+(.+)$/iu;

// "Evolves from" lines, Japanese evolution/rule sentences — skipped entirely.
const SKIP_LINE = /^(?:E(?:vo|va)lves?\s+from|.+から(?:進化)?|.+。|.+進化させます。?|「.*進化ポケモン.*)$/iu;

// Trailing level indicators: " LV.49", " x.15", " V.9", " .44".
const LEVEL_SUFFIX = /\s+(?:LV|Lv)\.\s*\d+$|\s+x\.\d+$|\s+V\.\d+$|\s+\.\d+$/giu;

// HP (plus type-symbol noise, or a garbled level token) read onto the name line.
const HP_SUFFIX = /\s+\d{2,4}$|\s+(?:\S{1,6}\s+)?HP\s*\d{2,3}\d?$/giu;

const SLASH_NUMBER = new RegExp(WB + '(\\d{1,3}/\\d{1,4}|TG\\d+/TG\\d+|\\d{1,3}/[A-Z]{1,6}-[A-Z])(?:[A-Z]{0,4})' + WB, 'iu');
const NO_NUMBER = new RegExp(WB + '(No\\.\\s*\\d{1,3})' + WB, 'iu');
const NO_CORRUPT = new RegExp(WB + 'N[a-z]\\.?\\s+(\\d{1,3})' + WB, 'iu');
const HP_PREFIX = new RegExp(WB + 'HP\\s*(\\d{2,3})\\d?' + WB, 'iu');
const HP_POSTFIX = new RegExp(WB + '(\\d{2,3})\\d?\\s*HP' + WB, 'iu');
const ILLUS = /^[A-Za-z]{0,4}lus\.?\s*(.+)/iu;

const codePointLength = s => [...s].length;
const stripLevel = name => name.replace(LEVEL_SUFFIX, '').trim();
const stripHp = name => name.replace(HP_SUFFIX, '').trim();

export function detectLanguage(rawText) {
 for (const ch of rawText) {
  const cp = ch.codePointAt(0);
  if ((cp >= 0x3040 && cp <= 0x309F) || (cp >= 0x30A0 && cp <= 0x30FF) || (cp >= 0x4E00 && cp <= 0x9FFF)) return 'JA';
 }
 return 'EN';
}

// Every line that could be the card name, top to bottom — the matcher tries them all.
function nameCandidates(lines) {
 const candidates = [], seen = new Set();
 for (const line of lines) {
  if (SKIP_LINE.test(line)) continue;
  const inline = line.match(INLINE_PREFIX);
  let candidate = inline ? inline[1].trim() : line;
  if (NON_NAME.test(candidate)) continue;
  candidate = stripHp(stripLevel(candidate)).trim();
  if (codePointLength(candidate) < 2) continue;
  const key = candidate.toLowerCase();
  if (!seen.has(key)) { seen.add(key); candidates.push(candidate); }
 }
 return candidates;
}

export function parsePokemonCardText(rawText) {
 const lines = rawText.split('\n').map(l => l.trim()).filter(Boolean);
 const result = {
  name: null,
  name_candidates: nameCandidates(lines),
  set_number: null,
  ocr_num1: null,
  ocr_num2: null,
  hp: null,
  illustrator: null,
  language_code: detectLanguage(rawText),
 };

 for (const line of lines) {
  if (SKIP_LINE.test(line)) continue;
  const inline = line.match(INLINE_PREFIX);
  if (inline) {
   const candidate = stripLevel(inline[1].trim());
   if (!NON_NAME.test(candidate)) { result.name = stripHp(candidate); break; }
   continue;
  }
  if (!NON_NAME.test(line)) { result.name = stripHp(stripLevel(line)); break; }
 }

 // Slash formats take priority over "No.NNN" so a Pokédex line can't shadow the set number.
 for (const line of lines) {
  const m = line.match(SLASH_NUMBER);
  if (m) {
   const parts = m[1].split('/');
   result.set_number = m[1];
   result.ocr_num1 = parts[0] ?? null;
   result.ocr_num2 = parts[1] ?? null;
   break;
  }
 }
 const setNoNumber = digits => { result.set_number = result.ocr_num1 = `No.${digits}`; result.ocr_num2 = null; };
 if (result.set_number === null) {
  for (const line of lines) {
   const m = line.match(NO_NUMBER);
   if (m) { setNoNumber(m[1].slice(3).trim()); break; }
  }
 }
 if (result.set_number === null) {
  for (const line of lines) {
   const m = line.match(NO_CORRUPT);
   if (m) { setNoNumber(m[1].trim()); break; }
  }
 }
 // Topsun / Vending-era cards print a lone zero-padded number.
 if (result.set_number === null) {
  const line = lines.find(l => /^0\d{2}$/.test(l));
  if (line) { result.set_number = result.ocr_num1 = line; result.ocr_num2 = null; }
 }

 // "HP 50" before "50 HP": a joint search would let "LV.15 HP 50" read as 15.
 const hp = rawText.match(HP_PREFIX) || rawText.match(HP_POSTFIX);
 if (hp) result.hp = parseInt(hp[1], 10);

 for (const line of lines) {
  const m = line.match(ILLUS);
  if (m) {
   let artist = m[1].trim();
   const copy = artist.indexOf('©');
   if (copy > 0) artist = artist.slice(0, copy).trim();
   result.illustrator = artist;
   break;
  }
 }
 return result;
}
